version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/cemara_db
      - JWT_SECRET=supersecret
    depends_on:
      - db
    networks:
      - cemara-net

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cemara_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cemara-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - cemara-net

networks:
  cemara-net:
    driver: bridge

volumes:
  pgdata:
